name: nota_music
description: Unofficial ya music client

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  kplayer: 0.2.4
  yandex_music_api_flutter:
    path: './yandex-music-api-flutter'
  iconsax: 0.0.8
  flutter_bloc: 8.0.1
  freezed_annotation: 2.0.3
  json_annotation: 4.5.0
  desktop_webview_window: 0.1.6 

  auto_route: 4.2.1
  
  rxdart: 0.27.4
  shared_preferences: 2.0.15

  grouped_list: ^5.1.2

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.1.11
  freezed: 2.0.3+1
  json_serializable: 6.2.0

  auto_route_generator: 4.2.1

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true